/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.VacinaController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vinic
 */
public class cadastroVacina extends javax.swing.JFrame {

    private final VacinaController controller;

    /**
     * Creates new form informaVacina
     */
    public cadastroVacina() {
        initComponents();
        controller = new VacinaController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastraVacinaNome = new javax.swing.JLabel();
        CadastraVacinaInsereNome = new javax.swing.JTextField();
        CadastraVacinaFabricante = new javax.swing.JLabel();
        CadastraVacinaInsereFabricante = new javax.swing.JTextField();
        CadastraVacinaOrigem = new javax.swing.JLabel();
        CadastraVacinaInsereOrigem = new javax.swing.JTextField();
        CadastrarVacinaEnvia = new javax.swing.JButton();
        BackgroundSistema = new javax.swing.JLabel();
        MenuTopo = new javax.swing.JMenuBar();
        MenuDados = new javax.swing.JMenu();
        MenuVacina = new javax.swing.JMenu();
        MenuPosto = new javax.swing.JMenu();
        MenuRelatorios = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Nacional de Jacarés");
        setResizable(false);
        getContentPane().setLayout(null);

        CadastraVacinaNome.setText("Nome da Vacina");
        getContentPane().add(CadastraVacinaNome);
        CadastraVacinaNome.setBounds(80, 40, 80, 40);

        CadastraVacinaInsereNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CadastraVacinaInsereNome.setText(" ");
        CadastraVacinaInsereNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraVacinaInsereNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CadastraVacinaInsereNome);
        CadastraVacinaInsereNome.setBounds(170, 40, 300, 40);

        CadastraVacinaFabricante.setText("Fabricante");
        getContentPane().add(CadastraVacinaFabricante);
        CadastraVacinaFabricante.setBounds(100, 100, 100, 40);

        CadastraVacinaInsereFabricante.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CadastraVacinaInsereFabricante.setText(" ");
        CadastraVacinaInsereFabricante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraVacinaInsereFabricanteActionPerformed(evt);
            }
        });
        getContentPane().add(CadastraVacinaInsereFabricante);
        CadastraVacinaInsereFabricante.setBounds(170, 100, 300, 40);

        CadastraVacinaOrigem.setText("Origem");
        getContentPane().add(CadastraVacinaOrigem);
        CadastraVacinaOrigem.setBounds(120, 160, 42, 40);

        CadastraVacinaInsereOrigem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CadastraVacinaInsereOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraVacinaInsereOrigemActionPerformed(evt);
            }
        });
        getContentPane().add(CadastraVacinaInsereOrigem);
        CadastraVacinaInsereOrigem.setBounds(170, 160, 300, 40);

        CadastrarVacinaEnvia.setText("Cadastrar Nova Vacina");
        CadastrarVacinaEnvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarVacinaEnviaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarVacinaEnvia);
        CadastrarVacinaEnvia.setBounds(300, 220, 170, 50);

        BackgroundSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundInternal.jpg"))); // NOI18N
        getContentPane().add(BackgroundSistema);
        BackgroundSistema.setBounds(-120, 0, 890, 390);

        MenuDados.setText("Enviar Dados de Vacinação        ");
        MenuDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDadosActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuDados);

        MenuVacina.setText("Cadastrar Nova Vacina        ");
        MenuVacina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuTopo.add(MenuVacina);

        MenuPosto.setText("Cadastrar Novo Posto de Vacinação        ");
        MenuPosto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPostoActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuPosto);

        MenuRelatorios.setText("Gerar Relatórios        ");
        MenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuTopo.add(MenuRelatorios);

        MenuSair.setText("Sair");
        MenuSair.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuSair);

        setJMenuBar(MenuTopo);

        setSize(new java.awt.Dimension(775, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSairActionPerformed

    private void CadastraVacinaInsereOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraVacinaInsereOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraVacinaInsereOrigemActionPerformed

    private void CadastraVacinaInsereNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraVacinaInsereNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraVacinaInsereNomeActionPerformed

    private void CadastraVacinaInsereFabricanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraVacinaInsereFabricanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraVacinaInsereFabricanteActionPerformed

    private void CadastrarVacinaEnviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarVacinaEnviaActionPerformed
        // TODO add your handling code here:
        this.controller.Executado();
    }//GEN-LAST:event_CadastrarVacinaEnviaActionPerformed

    private void MenuPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPostoActionPerformed
        cadastroPosto tela = TelaCadastroPosto();
            tela.setVisible(true);
    }//GEN-LAST:event_MenuPostoActionPerformed

    private void MenuDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDadosActionPerformed
        informaVacina tela = TelaSistema();
            tela.setVisible(true);
    }//GEN-LAST:event_MenuDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroVacina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundSistema;
    private javax.swing.JLabel CadastraVacinaFabricante;
    private javax.swing.JTextField CadastraVacinaInsereFabricante;
    private javax.swing.JTextField CadastraVacinaInsereNome;
    private javax.swing.JTextField CadastraVacinaInsereOrigem;
    private javax.swing.JLabel CadastraVacinaNome;
    private javax.swing.JLabel CadastraVacinaOrigem;
    private javax.swing.JButton CadastrarVacinaEnvia;
    private javax.swing.JMenu MenuDados;
    private javax.swing.JMenu MenuPosto;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuBar MenuTopo;
    private javax.swing.JMenu MenuVacina;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);

    }

    private cadastroPosto TelaCadastroPosto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private informaVacina TelaSistema() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JTextField getCadastraVacinaInsereFabricante() {
        return CadastraVacinaInsereFabricante;
    }

    public void setCadastraVacinaInsereFabricante(JTextField CadastraVacinaInsereFabricante) {
        this.CadastraVacinaInsereFabricante = CadastraVacinaInsereFabricante;
    }

    public JTextField getCadastraVacinaInsereNome() {
        return CadastraVacinaInsereNome;
    }

    public void setCadastraVacinaInsereNome(JTextField CadastraVacinaInsereNome) {
        this.CadastraVacinaInsereNome = CadastraVacinaInsereNome;
    }

    public JTextField getCadastraVacinaInsereOrigem() {
        return CadastraVacinaInsereOrigem;
    }

    public void setCadastraVacinaInsereOrigem(JTextField CadastraVacinaInsereOrigem) {
        this.CadastraVacinaInsereOrigem = CadastraVacinaInsereOrigem;
    }
    
    
}
