/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.PostoController;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vinic
 */
public class cadastroPosto extends javax.swing.JFrame {

    private final PostoController controller;

    /**
     * Creates new form informaVacina
     */
    public cadastroPosto() {
        initComponents();
        controller  = new PostoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastraPostoNome = new javax.swing.JLabel();
        CadastraPostoInsereNome = new javax.swing.JTextField();
        CadastraPostoMunicipio = new javax.swing.JLabel();
        CadastraPostoInsereMunicipio = new javax.swing.JComboBox<>();
        AdicionaMunicipio = new javax.swing.JLabel();
        CadastraPostoEstado = new javax.swing.JLabel();
        CadastraPostoInsereEstado = new javax.swing.JComboBox<>();
        CadastrarVacinaEnvia = new javax.swing.JButton();
        BackgroundSistema = new javax.swing.JLabel();
        MenuTopo = new javax.swing.JMenuBar();
        MenuDados = new javax.swing.JMenu();
        MenuVacina = new javax.swing.JMenu();
        MenuPosto = new javax.swing.JMenu();
        MenuRelatorios = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Nacional de Jacarés");
        setResizable(false);
        getContentPane().setLayout(null);

        CadastraPostoNome.setText("Nome do Posto");
        getContentPane().add(CadastraPostoNome);
        CadastraPostoNome.setBounds(100, 30, 80, 40);

        CadastraPostoInsereNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CadastraPostoInsereNome.setText(" ");
        CadastraPostoInsereNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastraPostoInsereNomeActionPerformed(evt);
            }
        });
        getContentPane().add(CadastraPostoInsereNome);
        CadastraPostoInsereNome.setBounds(180, 30, 290, 40);

        CadastraPostoMunicipio.setText("Município");
        getContentPane().add(CadastraPostoMunicipio);
        CadastraPostoMunicipio.setBounds(130, 90, 50, 40);

        CadastraPostoInsereMunicipio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CadastraPostoInsereMunicipio);
        CadastraPostoInsereMunicipio.setBounds(180, 90, 290, 40);

        AdicionaMunicipio.setText("+ Adicionar Município");
        getContentPane().add(AdicionaMunicipio);
        AdicionaMunicipio.setBounds(370, 130, 120, 20);

        CadastraPostoEstado.setText("Estado");
        getContentPane().add(CadastraPostoEstado);
        CadastraPostoEstado.setBounds(140, 160, 39, 40);

        CadastraPostoInsereEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(CadastraPostoInsereEstado);
        CadastraPostoInsereEstado.setBounds(180, 160, 290, 40);

        CadastrarVacinaEnvia.setText("Cadastrar Nova Vacina");
        CadastrarVacinaEnvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarVacinaEnviaActionPerformed(evt);
            }
        });
        getContentPane().add(CadastrarVacinaEnvia);
        CadastrarVacinaEnvia.setBounds(300, 220, 170, 50);

        BackgroundSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundInternal.jpg"))); // NOI18N
        getContentPane().add(BackgroundSistema);
        BackgroundSistema.setBounds(-120, 0, 890, 390);

        MenuDados.setText("Enviar Dados de Vacinação        ");
        MenuDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDadosActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuDados);

        MenuVacina.setText("Cadastrar Nova Vacina        ");
        MenuVacina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuTopo.add(MenuVacina);

        MenuPosto.setText("Cadastrar Novo Posto de Vacinação        ");
        MenuPosto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPostoActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuPosto);

        MenuRelatorios.setText("Gerar Relatórios        ");
        MenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuTopo.add(MenuRelatorios);

        MenuSair.setText("Sair");
        MenuSair.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuSair);

        setJMenuBar(MenuTopo);

        setSize(new java.awt.Dimension(775, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSairActionPerformed

    private void CadastraPostoInsereNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastraPostoInsereNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadastraPostoInsereNomeActionPerformed

    private void CadastrarVacinaEnviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarVacinaEnviaActionPerformed
        // TODO add your handling code here:
        this.controller.Executado();
    }//GEN-LAST:event_CadastrarVacinaEnviaActionPerformed

    private void MenuPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPostoActionPerformed
        cadastroPosto tela = TelaCadastroPosto();
            tela.setVisible(true);
    }//GEN-LAST:event_MenuPostoActionPerformed

    private void MenuDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDadosActionPerformed
        informaVacina tela = TelaSistema();
            tela.setVisible(true);
    }//GEN-LAST:event_MenuDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroPosto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroPosto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroPosto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroPosto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroPosto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdicionaMunicipio;
    private javax.swing.JLabel BackgroundSistema;
    private javax.swing.JLabel CadastraPostoEstado;
    private javax.swing.JComboBox<String> CadastraPostoInsereEstado;
    private javax.swing.JComboBox<String> CadastraPostoInsereMunicipio;
    private javax.swing.JTextField CadastraPostoInsereNome;
    private javax.swing.JLabel CadastraPostoMunicipio;
    private javax.swing.JLabel CadastraPostoNome;
    private javax.swing.JButton CadastrarVacinaEnvia;
    private javax.swing.JMenu MenuDados;
    private javax.swing.JMenu MenuPosto;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuBar MenuTopo;
    private javax.swing.JMenu MenuVacina;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);

    }

    private cadastroPosto TelaCadastroPosto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private informaVacina TelaSistema() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JComboBox<String> getCadastraPostoInsereEstado() {
        return CadastraPostoInsereEstado;
    }

    public void setCadastraPostoInsereEstado(JComboBox<String> CadastraPostoInsereEstado) {
        this.CadastraPostoInsereEstado = CadastraPostoInsereEstado;
    }

    public JComboBox<String> getCadastraPostoInsereMunicipio() {
        return CadastraPostoInsereMunicipio;
    }

    public void setCadastraPostoInsereMunicipio(JComboBox<String> CadastraPostoInsereMunicipio) {
        this.CadastraPostoInsereMunicipio = CadastraPostoInsereMunicipio;
    }

    public JTextField getCadastraPostoInsereNome() {
        return CadastraPostoInsereNome;
    }

    public void setCadastraPostoInsereNome(JTextField CadastraPostoInsereNome) {
        this.CadastraPostoInsereNome = CadastraPostoInsereNome;
    }

    public Object getCadastrarPostoInsereNome() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }



    private class controller {

        public controller() {
        }
    }
    
    
}
