/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controller.VacinacaoController;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author vinic
 */
public class informaVacina extends javax.swing.JFrame {

    private final VacinacaoController controller;

    /**
     * Creates new form TelaSistema
     */
    public informaVacina() {
        initComponents();
        controller = new VacinacaoController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DadosInsereVacina = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        DadosInsereData = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        DadosIdPosto = new javax.swing.JTextField();
        DadosBotaoEnvia = new javax.swing.JButton();
        BackgroundSistema = new javax.swing.JLabel();
        MenuTopo = new javax.swing.JMenuBar();
        MenuDados = new javax.swing.JMenu();
        MenuVacina = new javax.swing.JMenu();
        MenuPosto = new javax.swing.JMenu();
        MenuRelatorios = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Nacional de Jacarés");
        setResizable(false);
        getContentPane().setLayout(null);

        DadosInsereVacina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DadosInsereVacina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coronavac", "Oxford AstraZeneca", "Pfizer Biontech", "Sputnik V" }));
        getContentPane().add(DadosInsereVacina);
        DadosInsereVacina.setBounds(40, 40, 450, 40);

        jLabel1.setText("Data da Aplicação");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 100, 100, 40);

        DadosInsereData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DadosInsereData.setText(" ");
        DadosInsereData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DadosInsereDataActionPerformed(evt);
            }
        });
        getContentPane().add(DadosInsereData);
        DadosInsereData.setBounds(200, 100, 270, 40);

        jLabel2.setText("Registro Posto de Vacinação");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 160, 164, 40);

        DadosIdPosto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DadosIdPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DadosIdPostoActionPerformed(evt);
            }
        });
        getContentPane().add(DadosIdPosto);
        DadosIdPosto.setBounds(200, 160, 270, 40);

        DadosBotaoEnvia.setText("Enviar Dados de Vacinação");
        DadosBotaoEnvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DadosBotaoEnviaActionPerformed(evt);
            }
        });
        getContentPane().add(DadosBotaoEnvia);
        DadosBotaoEnvia.setBounds(300, 220, 170, 50);

        BackgroundSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/backgroundInternal.jpg"))); // NOI18N
        getContentPane().add(BackgroundSistema);
        BackgroundSistema.setBounds(-120, 0, 890, 390);

        MenuDados.setText("Enviar Dados de Vacinação        ");
        MenuDados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuTopo.add(MenuDados);

        MenuVacina.setText("Cadastrar Nova Vacina        ");
        MenuVacina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuVacina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuVacinaActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuVacina);

        MenuPosto.setText("Cadastrar Novo Posto de Vacinação        ");
        MenuPosto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPostoActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuPosto);

        MenuRelatorios.setText("Gerar Relatórios        ");
        MenuRelatorios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MenuTopo.add(MenuRelatorios);

        MenuSair.setText("Sair");
        MenuSair.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        MenuTopo.add(MenuSair);

        setJMenuBar(MenuTopo);

        setSize(new java.awt.Dimension(775, 353));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSairActionPerformed

    private void DadosIdPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DadosIdPostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DadosIdPostoActionPerformed

    private void DadosInsereDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DadosInsereDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DadosInsereDataActionPerformed

    private void MenuVacinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuVacinaActionPerformed
            cadastroVacina tela = TelaCadastroVacina();
            tela.setVisible(true);
    }//GEN-LAST:event_MenuVacinaActionPerformed

    private void MenuPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPostoActionPerformed
        cadastroPosto tela = TelaCadastroPosto();
            tela.setVisible(true);
    }//GEN-LAST:event_MenuPostoActionPerformed

    private void DadosBotaoEnviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DadosBotaoEnviaActionPerformed
        // TODO add your handling code here:
        this.controller.Executado();
    }//GEN-LAST:event_DadosBotaoEnviaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(informaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(informaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(informaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(informaVacina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new informaVacina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundSistema;
    private javax.swing.JButton DadosBotaoEnvia;
    private javax.swing.JTextField DadosIdPosto;
    private javax.swing.JTextField DadosInsereData;
    private javax.swing.JComboBox<String> DadosInsereVacina;
    private javax.swing.JMenu MenuDados;
    private javax.swing.JMenu MenuPosto;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuBar MenuTopo;
    private javax.swing.JMenu MenuVacina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);

    }
    
    private cadastroVacina TelaCadastroVacina() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private cadastroPosto TelaCadastroPosto() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public JTextField getDadosIdPosto() {
        return DadosIdPosto;
    }

    public void setDadosIdPosto(JTextField DadosIdPosto) {
        this.DadosIdPosto = DadosIdPosto;
    }

    public JTextField getDadosInsereData() {
        return DadosInsereData;
    }

    public void setDadosInsereData(JTextField DadosInsereData) {
        this.DadosInsereData = DadosInsereData;
    }

    public JComboBox<String> getDadosInsereVacina() {
        return DadosInsereVacina;
    }

    public void setDadosInsereVacina(JComboBox<String> DadosInsereVacina) {
        this.DadosInsereVacina = DadosInsereVacina;
    }
    
    
}
